#!/usr/bin/env python3
"""alfa-migrate — one-command RAGE MP → Alfa MP server migration orchestrator.

Wraps rage2alfa.py (folder + file conversion) + asset categorization + dep
installation + resource manifest emission + AlfaServer drop-in instructions.

Usage:
    python alfa-migrate.py /path/to/rage-server  [--out /path/to/alfa-server-data]
                                                  [--target server-data/resources]

What this does step by step:
    1. Scans the RAGE-MP server tree (packages/, client_packages/, conf.json…)
    2. Splits per-resource into separate AlfaMP resources under <out>/
    3. For each:
        a. Reads _resource.toml / conf.json → emits fxmanifest.lua
        b. Server-side .cs / .js → server/  (auto-prepends compat-shim require)
        c. Client-side .js → client/  (auto-injects ragemp-client-shim)
        d. CEF .html/.css/.js → html/  (works via NUI bridge)
        e. .ymap / .ytyp / .ydr / .ytd / .ydd / .yft → stream/
    4. npm install of @alfamp/ragemp-shim + @alfamp/ragemp-client-shim
    5. Writes MIGRATION-REPORT.md with the list of API-calls our shim can't
       yet handle (so the hoster knows what to fix manually)

After this, drop the output folder into /opt/alfaserver/server-data/resources/
and `ensure <name>` in server.cfg.
"""
import argparse, json, re, shutil, sys, subprocess, hashlib
from pathlib import Path

try:
    import tomllib
except ImportError:
    tomllib = None

STREAM_EXTS = {'.ymap', '.ymf', '.ymt', '.ytyp', '.ydr', '.ydd', '.yft', '.ytd', '.ynd', '.ynv',
               '.awc', '.gxt2', '.gfx', '.rpf', '.dat'}
CS_EXTS     = {'.cs', '.csproj'}
JS_EXTS     = {'.js', '.mjs'}
UI_EXTS     = {'.html', '.htm', '.css', '.svg', '.png', '.jpg', '.jpeg', '.gif', '.webp',
               '.woff', '.woff2', '.ttf', '.json'}

# RAGE-MP-only API calls we don't yet bridge — surfaced in MIGRATION-REPORT.md
KNOWN_UNCOVERED = [
    r'mp\.voiceChat\b',
    r'mp\.discord\b',
    r'mp\.peds\b',                          # We have basic Peds but limited
    r'mp\.network\.startBatch',
    r'mp\.gui\.cursor\b',
    r'mp\.raycasting\.testCapsule',
]

def parse_meta(src: Path) -> dict:
    for name, parser in [('_resource.toml', lambda t: tomllib.loads(t) if tomllib else {}),
                          ('_resource.json', lambda t: json.loads(t)),
                          ('package.json', lambda t: json.loads(t))]:
        p = src / name
        if p.exists():
            try: return parser(p.read_text(encoding='utf-8'))
            except Exception as e: print(f'  warn: failed to parse {name}: {e}')
    return {}

def make_resource_dir(out_root: Path, name: str) -> Path:
    p = out_root / name
    for sub in ('server', 'client', 'html', 'stream'):
        (p / sub).mkdir(parents=True, exist_ok=True)
    return p

def write_manifest(res_dir: Path, name: str, meta: dict):
    lines = [
        "fx_version 'cerulean'",
        "game 'gta5'",
        "",
        f"author '{meta.get('author', 'Migrated from RAGE MP via alfa-migrate')}'",
        f"description '{meta.get('description', name)}'",
        f"version '{meta.get('version', '1.0.0')}'",
        "",
        "-- Server scripts (compat shim auto-required by injected wrapper)",
        "server_scripts {",
        "    'server/_alfa_bootstrap.js',",
        "    'server/*.js',",
        "    'server/*.cs',",
        "    'server/*.dll',",
        "}",
        "",
        "client_scripts {",
        "    'client/_alfa_bootstrap.js',",
        "    'client/*.js',",
        "}",
        "",
    ]
    if any((res_dir / 'html').glob('*.html')):
        ui = next((p for p in (res_dir / 'html').glob('*.html')), None)
        lines += [f"ui_page 'html/{ui.name}'", ""]
    lines += [
        "files {",
        "    'stream/**/*',",
        "    'html/**/*',",
        "}",
        "",
        "this_is_a_map 'no'",
        "use_experimental_fxv2_oal 'yes'",
    ]
    (res_dir / 'fxmanifest.lua').write_text('\n'.join(lines), encoding='utf-8')

SERVER_BOOTSTRAP = """// AUTO-GENERATED by alfa-migrate. Loads bundled RAGE-MP shim BEFORE your code.
// NO npm install needed — shim is a single file shipped right next to this.
'use strict';
require('./alfa_shim_bundle.js');
console.log('[alfa-migrate] mp.* shim installed for this resource (bundled, no npm needed)');
"""

CLIENT_BOOTSTRAP = """// AUTO-GENERATED by alfa-migrate. Loads bundled client-side shim.
// NO npm install needed — shim files are right next to this one.
require('./alfa_client_shim_bundle.js');
"""

def categorise_files(src: Path, dst: Path) -> dict:
    """Returns metrics: counted file kinds.

    Deep-scans nested dirs for stream assets (RAGE puts maps under packages/<res>/maps/
    or client_packages/maps/, both get walked recursively here)."""
    counts = {'server_cs': 0, 'server_js': 0, 'client_js': 0, 'ui': 0, 'stream': 0, 'skipped': 0}
    for p in src.rglob('*'):
        if p.is_dir() or p.name.startswith('_resource.') or p.name == 'conf.json': continue
        rel = p.relative_to(src)
        ext = p.suffix.lower()
        is_client = any(part.lower() in ('client_packages', 'client') for part in rel.parts[:-1])
        # Also: streams can live under any "maps", "stream", "interiors", "vehicles" dir
        is_stream_dir = any(part.lower() in ('maps', 'stream', 'interiors', 'vehicles', 'props', 'peds', 'weapons')
                            for part in rel.parts[:-1])

        if ext in STREAM_EXTS or (is_stream_dir and ext not in JS_EXTS | CS_EXTS | UI_EXTS):
            # Anything in a streaming-named dir that isn't code → stream
            tgt = dst / 'stream' / rel.name  # flatten — CFX streaming engine reads flat
            tgt.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, tgt); counts['stream'] += 1
        elif ext in CS_EXTS:
            (dst / 'server' / rel.name).write_bytes(p.read_bytes()); counts['server_cs'] += 1
        elif ext in JS_EXTS:
            target = 'client' if is_client else 'server'
            (dst / target / rel.name).write_bytes(p.read_bytes())
            counts['client_js' if is_client else 'server_js'] += 1
        elif ext in UI_EXTS:
            tgt = dst / 'html' / rel
            tgt.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, tgt); counts['ui'] += 1
        else:
            counts['skipped'] += 1
    return counts

# Path to bundled shim files (next to this script): ../dist/alfa_*_bundle.js
BUNDLED_SHIMS_DIR = Path(__file__).resolve().parent.parent / 'dist'

def copy_bundled_shims(dst: Path) -> dict:
    """Copy the SELF-CONTAINED shim files into the resource so NO npm install is needed.
    Server gets alfa_shim_bundle.js; client gets alfa_client_shim_bundle.js + alfa_natives_map.js."""
    out = {'server_shim': False, 'client_shim': False}
    server_shim = BUNDLED_SHIMS_DIR / 'alfa_shim_bundle.js'
    client_shim = BUNDLED_SHIMS_DIR / 'alfa_client_shim_bundle.js'
    natives_map = BUNDLED_SHIMS_DIR / 'alfa_natives_map.js'
    if server_shim.exists():
        shutil.copy2(server_shim, dst / 'server' / 'alfa_shim_bundle.js')
        out['server_shim'] = True
    if client_shim.exists():
        shutil.copy2(client_shim, dst / 'client' / 'alfa_client_shim_bundle.js')
        out['client_shim'] = True
    if natives_map.exists():
        shutil.copy2(natives_map, dst / 'client' / 'alfa_natives_map.js')
    return out

HEARTBEAT_SH = """#!/bin/bash
# AUTO-GENERATED by alfa-migrate. Pings our master every 20 s to keep server visible in launcher.
# Edit SERVER_ID and API_KEY below with values from http://104.194.140.221:8080/admin

SERVER_ID="REPLACE_WITH_ID_FROM_ADMIN"
API_KEY="REPLACE_WITH_API_KEY_FROM_ADMIN"
MASTER_URL="http://104.194.140.221:8080"
SERVER_PORT="30120"

PLAYERS=$(curl -sS --max-time 3 "http://127.0.0.1:${SERVER_PORT}/players.json" \\
  | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))' 2>/dev/null || echo 0)

curl -sS -X POST "${MASTER_URL}/v1/servers/heartbeat" \\
  -H 'Content-Type: application/json' \\
  -d "{\\"serverId\\":\\"$SERVER_ID\\",\\"apiKey\\":\\"$API_KEY\\",\\"players\\":$PLAYERS}" \\
  | tail -c 200
"""

HEARTBEAT_SVC = """[Unit]
Description=Alfa MP server heartbeat (keeps server visible in launcher)

[Service]
Type=oneshot
ExecStart=/opt/alfaserver/heartbeat.sh
"""

HEARTBEAT_TIMER = """[Unit]
Description=Alfa MP heartbeat every 20 s

[Timer]
OnBootSec=10s
OnUnitActiveSec=20s
AccuracySec=2s
Unit=alfaserver-heartbeat.service

[Install]
WantedBy=timers.target
"""

INSTALL_HEARTBEAT_SH = """#!/bin/bash
# AUTO-GENERATED by alfa-migrate. Run as root on your AlfaServer VPS:
#   sudo bash install-heartbeat.sh
#
# Installs heartbeat.sh + systemd timer that pings our master every 20 s.
set -e
cd "$(dirname "$0")"

echo "=== Installing heartbeat.sh to /opt/alfaserver/ ==="
sudo install -m 0755 heartbeat.sh /opt/alfaserver/heartbeat.sh

echo "=== Installing systemd units ==="
sudo install -m 0644 alfaserver-heartbeat.service /etc/systemd/system/
sudo install -m 0644 alfaserver-heartbeat.timer   /etc/systemd/system/

echo "=== Reload + enable timer ==="
sudo systemctl daemon-reload
sudo systemctl enable --now alfaserver-heartbeat.timer

echo
echo "✅ Heartbeat installed and running."
echo "   Verify: sudo systemctl status alfaserver-heartbeat.timer"
echo "   Edit /opt/alfaserver/heartbeat.sh and replace SERVER_ID + API_KEY"
echo "   (values from http://104.194.140.221:8080/admin)."
"""

def emit_heartbeat_kit(out_root: Path):
    """Write ready-to-deploy heartbeat scripts to <out>/_heartbeat-kit/"""
    kit = out_root / '_heartbeat-kit'
    kit.mkdir(exist_ok=True)
    (kit / 'heartbeat.sh').write_text(HEARTBEAT_SH)
    (kit / 'alfaserver-heartbeat.service').write_text(HEARTBEAT_SVC)
    (kit / 'alfaserver-heartbeat.timer').write_text(HEARTBEAT_TIMER)
    (kit / 'install-heartbeat.sh').write_text(INSTALL_HEARTBEAT_SH)
    # Make scripts executable on POSIX
    for f in ('heartbeat.sh', 'install-heartbeat.sh'):
        try: (kit / f).chmod(0o755)
        except Exception: pass

def scan_uncovered(dst: Path):
    """Find RAGE-only API references our shim doesn't cover."""
    findings = []
    for js in list((dst / 'server').rglob('*.js')) + list((dst / 'client').rglob('*.js')):
        text = js.read_text(encoding='utf-8', errors='replace')
        for pattern in KNOWN_UNCOVERED:
            for m in re.finditer(pattern, text):
                line_no = text.count('\n', 0, m.start()) + 1
                findings.append((js.relative_to(dst), line_no, m.group(0)))
    return findings

def emit_report(dst: Path, counts: dict, uncovered: list, meta: dict):
    parts = [
        f"# Migration report for `{dst.name}`",
        "",
        f"Original meta: {json.dumps(meta, indent=2) if meta else '(none)'}",
        "",
        "## File counts",
        "",
        f"- server (C#):  **{counts['server_cs']}** files",
        f"- server (JS):  **{counts['server_js']}** files",
        f"- client (JS):  **{counts['client_js']}** files",
        f"- UI / CEF:     **{counts['ui']}** files",
        f"- Streaming:    **{counts['stream']}** files (.ymap/.ytyp/.ydr/.ytd/…)",
        f"- Skipped:      {counts['skipped']} (unknown extension)",
        "",
        "## What works out of the box",
        "",
        "- `mp.players.*`, `mp.vehicles.*`, `mp.events.*`, `mp.world.*` (server)",
        "- `mp.gui.chat.*`, `new mp.Browser(...)`, `mp.events.callRemote(...)` (client)",
        "- All your `stream/` content (`.ymap`, `.ytyp`, `.ydr`, `.ytd`, …) streams as-is",
        "- HTML/JS/CSS in `html/` renders through NUI (identical Chromium engine as CEF)",
        "",
        "## What needs manual review",
        "",
    ]
    if not uncovered:
        parts += ["✅ No known-uncovered API calls detected. You're likely good.", ""]
    else:
        parts += [f"⚠️ Detected {len(uncovered)} call(s) to RAGE-only APIs our shim doesn't cover yet:", ""]
        parts += [f"- `{path}` line {ln}: `{snippet}`" for path, ln, snippet in uncovered]
        parts += [
            "",
            "Workarounds:",
            "- **mp.voiceChat**: install Mumble-compat resource (see docs/MAPS.md → voice section)",
            "- **mp.discord**: add `discord-rpc-compat` resource (separate NuGet)",
            "- **mp.peds**: most ped APIs work via natives — use `mp.game.invoke('CREATE_PED', ...)`",
            "- Other: file an issue at https://github.com/orientalagency8-gif/alfamp/issues with the line",
        ]
    parts += [
        "",
        "## Deploy",
        "",
        "```bash",
        f"cp -r {dst.name} /opt/alfaserver/server-data/resources/",
        "cd /opt/alfaserver/server-data/resources/" + dst.name,
        "npm install",   # if server has Node deps + compat shim
        f"echo 'ensure {dst.name}' >> /opt/alfaserver/server-data/server.cfg",
        "systemctl restart alfaserver",
        "```",
    ]
    (dst / 'MIGRATION-REPORT.md').write_text('\n'.join(parts), encoding='utf-8')

def write_package_json(dst: Path, original_pkg: dict):
    """Emit a minimal package.json — Alfa shim is BUNDLED (no @alfamp/ npm deps).
    Original user deps (mysql2, ioredis, etc) are preserved so `npm install` is needed
    ONLY IF the user's gamemode had third-party deps. If empty deps → no npm install
    needed at all."""
    orig_deps = (original_pkg.get('dependencies') or {})
    pkg = {
        "name": dst.name,
        "version": "1.0.0-alfa-migrated",
        "private": True,
        # NOTE: shim is in server/alfa_shim_bundle.js and client/alfa_client_shim_bundle.js
        # — no @alfamp/* npm dep needed. Only user's third-party deps below.
        "dependencies": orig_deps,
    }
    (dst / 'package.json').write_text(json.dumps(pkg, indent=2), encoding='utf-8')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", type=Path, help="Path to RAGE-MP server folder (the one with packages/)")
    ap.add_argument("--out", type=Path, default=None, help="Output folder (default: <src>-alfa)")
    args = ap.parse_args()

    src = args.src.resolve()
    if not src.is_dir(): print(f"Not a directory: {src}", file=sys.stderr); sys.exit(1)
    out = (args.out or src.with_name(src.name + '-alfa')).resolve()
    out.mkdir(parents=True, exist_ok=True)

    print(f"=== alfa-migrate v0.2 ===")
    print(f"  src: {src}")
    print(f"  out: {out}")

    # If packages/ exists → multi-resource RAGE server, migrate each
    pkg_dir = src / 'packages'
    if pkg_dir.is_dir():
        resources = [p for p in pkg_dir.iterdir() if p.is_dir()]
        print(f"  detected {len(resources)} RAGE packages → migrating each as separate Alfa resource\n")
    else:
        resources = [src]
        print(f"  treating root as single resource\n")

    summary = []
    for res_src in resources:
        name = re.sub(r'[^a-z0-9_-]', '-', res_src.name.lower())
        print(f"--- migrating {res_src.name} → {name} ---")
        res_dst = make_resource_dir(out, name)
        meta = parse_meta(res_src)
        counts = categorise_files(res_src, res_dst)
        (res_dst / 'server' / '_alfa_bootstrap.js').write_text(SERVER_BOOTSTRAP)
        (res_dst / 'client' / '_alfa_bootstrap.js').write_text(CLIENT_BOOTSTRAP)
        # Fix #1 — drop bundled shim next to bootstrap (no npm needed)
        shim_status = copy_bundled_shims(res_dst)
        if not (shim_status['server_shim'] and shim_status['client_shim']):
            print(f"  ⚠️  bundled shims not found at {BUNDLED_SHIMS_DIR}; falling back to npm-dep mode")
        write_manifest(res_dst, name, meta)
        write_package_json(res_dst, meta if isinstance(meta, dict) else {})
        uncovered = scan_uncovered(res_dst)
        emit_report(res_dst, counts, uncovered, meta if isinstance(meta, dict) else {})
        print(f"  counts: {counts}  uncovered: {len(uncovered)}")
        summary.append((name, counts, uncovered))

    # Fix #6 — emit ready-to-use heartbeat kit at the top level
    emit_heartbeat_kit(out)
    print(f"\n📦 heartbeat kit emitted at {out / '_heartbeat-kit/'}")

    # Top-level summary
    print(f"\n=== DONE ===")
    total_uncov = sum(len(u) for _, _, u in summary)
    print(f"  resources:        {len(summary)}")
    print(f"  total uncovered:  {total_uncov}")
    print(f"  output:           {out}")
    print(f"\n  Next: rsync to /opt/alfaserver/server-data/resources/ on your VPS, then:")
    for name, _, _ in summary:
        print(f"    echo 'ensure {name}' >> /opt/alfaserver/server-data/server.cfg")
    print(f"    systemctl restart alfaserver")
    print(f"\n  Read each {{resource}}/MIGRATION-REPORT.md for review notes.")

if __name__ == "__main__":
    main()
