#!/usr/bin/env python3
"""rage2alfa — convert a RAGE MP resource folder to an Alfa MP (FXServer) resource.

Usage:
    python rage2alfa.py /path/to/rage-resource [--out /path/to/alfa-resource]

What it does:
    1. Reads RAGE's `_resource.toml` (or `_resource.json`) → writes `fxmanifest.lua`.
    2. Copies C# server scripts into `server/`.
    3. Copies client scripts (JS) into `client/`.
    4. Copies CEF (UI) html/js/css into `html/`.
    5. Copies streamed assets (.ymap, .ytyp, .ydr, …) into `stream/`.
    6. Patches obvious incompatibilities in C# source (using directives are kept;
       compat layer makes them resolve).

What it does NOT do:
    * Translate RAGE-only natives (`mp.world.time.set`-style) — those are handled
      at RUNTIME by the AlfaMP.RageMP.Compat NuGet package.
    * Convert CEF -> NUI message channels — that needs manual review for ~10 LOC
      changes (template auto-emitted next to each .html file).
"""
import argparse, json, re, shutil, sys
from pathlib import Path

try:
    import tomllib  # Py 3.11+
except ImportError:
    tomllib = None

STREAM_EXTS = {'.ymap', '.ymf', '.ymt', '.ytyp', '.ydr', '.ydd', '.yft', '.ytd', '.ynd', '.ynv',
               '.awc', '.gxt2', '.gfx', '.rpf'}
CSHARP_EXTS  = {'.cs', '.csproj', '.dll'}
WEB_EXTS     = {'.html', '.htm', '.css', '.js', '.jsx', '.ts', '.tsx', '.svg', '.png', '.jpg', '.woff', '.woff2'}

def parse_meta(src: Path) -> dict:
    toml = src / "_resource.toml"
    js = src / "_resource.json"
    if toml.exists():
        if tomllib is None:
            print("ERROR: Python 3.11+ required for TOML parsing (or install tomli).", file=sys.stderr); sys.exit(1)
        return tomllib.loads(toml.read_text(encoding="utf-8"))
    if js.exists():
        return json.loads(js.read_text(encoding="utf-8"))
    print(f"WARNING: neither _resource.toml nor _resource.json found in {src}; emitting bare fxmanifest")
    return {}

def emit_manifest(out: Path, meta: dict, name: str):
    server = meta.get("server-files") or meta.get("server_scripts") or []
    client = meta.get("client-files") or meta.get("client_scripts") or []
    streams = meta.get("files") or []
    deps   = meta.get("dependencies") or []

    lines = [
        "fx_version 'cerulean'",
        "game 'gta5'",
        "",
        f"author '{meta.get('author', 'migrated from RAGE MP')}'",
        f"description '{meta.get('description', name)}'",
        f"version '{meta.get('version', '1.0.0')}'",
        "",
    ]
    if deps:
        lines += [f"dependency '{d}'" for d in deps] + [""]

    # Server: load any .dll/.net we copied
    lines += ["server_scripts {"]
    lines += [f"    '{s}'," for s in ["server/*.dll", "server/*.cs"]]
    lines += ["}", ""]

    # Client
    if client:
        lines += ["client_scripts {"]
        lines += [f"    '{c}'," for c in client]
        lines += ["}", ""]

    # UI page
    ui = next((Path(p).name for p in (meta.get("ui") or []) if str(p).endswith('.html')), None)
    if ui:
        lines += [f"ui_page 'html/{ui}'", ""]

    # Streams
    lines += [
        "files {",
        "    'stream/**/*',",
        "    'html/**/*',",
        "}",
        "",
        "this_is_a_map 'no'",
        "use_experimental_fxv2_oal 'yes'",
        "",
        "-- Generated by rage2alfa. Tweak as needed.",
    ]
    (out / "fxmanifest.lua").write_text("\n".join(lines), encoding="utf-8")

def categorize(src_root: Path, target: Path):
    target_server = target / "server"; target_server.mkdir(exist_ok=True)
    target_client = target / "client"; target_client.mkdir(exist_ok=True)
    target_html   = target / "html";   target_html.mkdir(exist_ok=True)
    target_stream = target / "stream"; target_stream.mkdir(exist_ok=True)

    for p in src_root.rglob('*'):
        if p.is_dir() or p.name.startswith('_resource.'): continue
        rel = p.relative_to(src_root)
        ext = p.suffix.lower()
        if ext in CSHARP_EXTS:
            (target_server / rel.name).write_bytes(p.read_bytes())
        elif ext in STREAM_EXTS:
            tgt = target_stream / rel; tgt.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, tgt)
        elif ext in WEB_EXTS:
            tgt = target_html / rel; tgt.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, tgt)
        elif ext in {'.js', '.ts'}:
            (target_client / rel.name).write_bytes(p.read_bytes())

# Light source patches — non-destructive
CS_PATCHES = [
    # `mp.something` (JS-style RAGE) → not used in C#; nothing to patch most of the time.
    # Identifier renames that ARE common:
    (re.compile(r'\bNAPI\.Util\.'), 'NAPI.'),  # NAPI.Util.* was deprecated mid-RAGE; collapse.
]

def patch_csharp(target: Path):
    for cs in (target / "server").rglob("*.cs"):
        text = cs.read_text(encoding="utf-8", errors="replace")
        original = text
        for rx, repl in CS_PATCHES:
            text = rx.sub(repl, text)
        if text != original:
            cs.write_text(text, encoding="utf-8")
            print(f"  patched: {cs.name}")

def emit_nui_hint(target: Path):
    html_dir = target / "html"
    if not any(html_dir.rglob("*.html")): return
    hint = """\
RAGE → NUI migration notes (read me!)
══════════════════════════════════════

Your CEF UI files were copied to `html/`. They mostly work as-is, but
**postMessage** patterns differ:

  RAGE:  `mp.invoke('eventName', data)`   ← client → server
  Alfa:  `fetch(`https://${resource}/eventName`, {method:'POST', body: JSON.stringify(data)})`

  RAGE:  `mp.events.add('foo', (data) => …)`    ← server → client UI
  Alfa:  `window.addEventListener('message', e => { if (e.data.type === 'foo') … })`

Server-side from the C# resource you trigger UI events with:
  SetNuiFocus(player, true, true);
  SendNuiMessage(player, JSON.stringify(new { type = "foo", payload = ... }));
"""
    (html_dir / "MIGRATION-NOTES.txt").write_text(hint, encoding="utf-8")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", type=Path, help="Path to RAGE MP resource folder")
    ap.add_argument("--out", type=Path, default=None, help="Output folder (default: <src>-alfa)")
    args = ap.parse_args()

    src = args.src.resolve()
    if not src.is_dir(): print(f"Not a directory: {src}", file=sys.stderr); sys.exit(1)
    out = (args.out or src.with_name(src.name + "-alfa")).resolve()
    out.mkdir(parents=True, exist_ok=True)

    print(f"=== rage2alfa ===")
    print(f"  src: {src}")
    print(f"  out: {out}\n")

    meta = parse_meta(src)
    print(f"  meta: {len(meta)} keys")

    print(f"\n[1/4] Categorising files…")
    categorize(src, out)
    print(f"[2/4] Patching C# source…")
    patch_csharp(out)
    print(f"[3/4] Emitting fxmanifest.lua…")
    emit_manifest(out, meta, src.name)
    print(f"[4/4] Emitting NUI migration hint…")
    emit_nui_hint(out)
    print(f"\nDone. Next steps:")
    print(f"  1. Add NuGet ref `AlfaMP.RageMP.Compat` to your .csproj (if you have one).")
    print(f"  2. Copy `{out.name}` to your alfaserver's `server-data/resources/`.")
    print(f"  3. Add `ensure {out.name}` to server.cfg.")
    print(f"  4. Restart server. Open html/MIGRATION-NOTES.txt for UI tweaks.")

if __name__ == "__main__":
    main()
